### ISSUE TITLE
[CHORE] 서버 통신 완료 확인 작업

### ISSUE THREAD

**Issue by SunYerim** [pknu-wap/2023_1_WAT_BeJuRyu#106]
## 📑 작업 사항 
서버 통신 완료 확인 작업

## To-do
- [x] 이름별 주류 리스트 조회
- [x] 감정분석 소스 등록
- [x] 주류 정보 요청
- [x] 타입별
- [x] 랭킹
- [x] 리뷰 등록
- [x] 리뷰 조회
- [x] 평점 조회

# #✔️ 기타사항
