### ISSUE TITLE
[FEATURE] 홈 화면 Ui 수정 및 홈 화면 랭킹 평점 구현

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_1_WAT_BeJuRyu#119]
## 📑 작업 사항 
홈 화면 ui 수정,
평점이 포함 된 Rank Model 구현하여, UI model Drink -> Rank로 변경하기 

## To-do
- [x] 홈 화면 ui 수정 
- [x] Rank Model 구현 
- [x] Drink -> Rank Model 변경

# #✔️ 기타사항
