### ISSUE TITLE
[FEATURE] 개인 히스토리 페이지 구현하기 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_1_WAT_BeJuRyu#14]
## 📑 작업 사항 
개인 히스토리 구현하기 

## To-do
- [x] user history list 받아오기 
- [x] 가져온 id 값으로 상세 정보 가져오기 
- [x] History Ui 구성

# #✔️ 기타사항
