### ISSUE TITLE
[FEATURE] 분석 결과 페이지 ui 수정 및 dto, model 변경

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_1_WAT_BeJuRyu#146]
## 📑 작업 사항 
분석 결과에서 이전에 작성한 결과 볼 수 있도록 설정
dto, model 변경으로 인해 수정 

## To-do
- [x] dto, model 수정 
- [x] 분석 결과 ui에 이전 사용자 입력 정보 추가
- [x]  결과 받아서 mapping

# #✔️ 기타사항
