### ISSUE TITLE
[FEATURE] 사진 입력 화면 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_1_WAT_BeJuRyu#20]
## 📑 작업 사항 
분석을 위한 사용자 사진 입력 화면 구현 

## To-do
- [x] 카메라, 앨범 디펜던시, 새로운 모듈 추가 
- [x] 카메라 기능 구현 
- [x] 앨범 사진 접근 기능 구현 
- [x] 각 화면간 전환 설정 

# #✔️ 기타사항
뿌쓩빠쓩
analyze module 
Camerax
PhotoPicker

**Comment by jeongjaino** [comment]
home -> text input -> choose dialog -> camera(permission) or album -> result
