### ISSUE TITLE
[FEATURE] Drink Service & Controller 작성

### ISSUE THREAD

**Issue by nuyh99** [pknu-wap/2023_1_WAT_BeJuRyu#36]
## 📑 작업 사항 
작업할 내용 설명 

## To-do
- [ ] 서비스 레이어 작성
- [ ] 서비스 레이어 테스트
- [ ] 컨트롤러 레이어 작성

# #✔️ 기타사항
생성자 주입으로 필요한 Repository 클래스를 주입 받아 사용한다.
서비스 레이어의 역할은??

서비스 레이어를 테스트하려면 Repository 의존성이 필요하다. 그렇다면 @SpringBootTest를 해야 할까?? Mockito??
Hint: 통합테스트와 Mocking(Stubbing)의 차이, 해당 메서드에서 검증하고 싶은 내용?

**Comment by onegqueen** [comment]
.
