### ISSUE TITLE
[FEATURE] 주류사전 메인 리스트 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_1_WAT_BeJuRyu#38]
## 📑 작업 사항 
주류 사전 모듈 생성 및 기능 구현 

## To-do
- [x] 사전 모듈 생성 
- [x] drink list api 로직 구현 
- [x] dictionary ui 구현 및 데이터 매핑 

# #✔️ 기타사항
