### ISSUE TITLE
[FEATURE] 화면 전환 설정

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_1_WAT_BeJuRyu#42]
## 📑 작업 사항 
앱 내의 화면 전환 설정 

## To-do
- [ ] app module 에서 통합 nav 만들기 
- [ ] bottom navigation 구현
- [x] intent를 활용한 전환 설정 

# #✔️ 기타사항
bottom navigation bar 활용, 
setting, auth의 경우 activity context 필요, 이의 경우 intent를 활용해 넘기기
나머지는 Navigation Componet 활용

**Comment by jeongjaino** [comment]
bottom navigation view 때려치웠음. 내 생에 SAA는 없고, 하나의 Container는 없다,,
