### ISSUE TITLE
[FEATURE] 주류 추천 결과 페이지

### ISSUE THREAD

**Issue by SunYerim** [pknu-wap/2023_1_WAT_BeJuRyu#49]
## 📑 작업 사항 
주류 추천 결과 페이지를 생성하고, 기분 입력화면에서 사진 첨부 가능하게끔하는 기능도 추가한다.

## To-do
- [x] 주류 추천 결과 페이지
- [x] 사진 첨부 기능 구현
- [x] 마이 페이지 ui 구현
- [x] 중간 발표 전까지 할 수 있는 작업들 (header 수정, style 수정 etc)

# #✔️ 기타사항
일단 해당 브랜치로 중간발표 전까지 했던 작업들을 다 병합후, 추후에 기능별로 더 덧붙여서 브랜치 생성하겠슴다
