### ISSUE TITLE
[FEATURE] (주류 사전) 주류 정보 페이지 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_1_WAT_BeJuRyu#59]
## 📑 작업 사항 
주류 리스트에서 선택한 주류에 대한 정보 페이지 구현 

## To-do
- [x] 주류 정보 페이지 ui 구성 
- [x] 리스트 -> 정보 페이지 이동시 얻은 id값으로 정보 호출 
- [x] 해당 정보 ui 매핑 

# #✔️ 기타사항
