### ISSUE TITLE
[TEST] 로그인 전체 과정 이해

### ISSUE THREAD

**Issue by SunYerim** [pknu-wap/2023_1_WAT_BeJuRyu#67]
## 📑 작업 사항 
testtest~ 공부하는 데 필요한 코드를 추가하였으나, 추후 사용이 될 수도 있는 코드도 있어 일단 commit 해둡니닷

## To-do
- [x] logout 컴포넌트 구현하여 로그인 상태가 유지된 상태로 서비스 제공이 되는지 확인
- [x] 소셜 로그인, 서버와의 통신방법(카카오 토큰 넘겨주고 jwt 토큰 받고...등등 그외), 회원가입이 되는 과정 로직 완전한 이해(현재 85프로정도 이해)
- [x] redux의 사용이 필수인가?에 대한 고민 (닉네임 변경도 없고 마이페이지에서만 닉네임을 띄워준다면 음..)
- [x] 각 파일 TODO 리스트 작성

# #✔️ 기타사항
카카오 소셜 로그인을 통한 카카오 토큰 발급까지는 완료되어 localstorage에 저장시켜놓고 작업을 진행하였으나
추후 비주류 서비스 자체 토큰으로 서비스가 되어야되므로 이를 이해하는데 여러가지 테스트를 해보았음.

토큰 요구의 유무로  서버와 통신이 되는 것들.. 등등 기초세팅은 해둔 상태이므로 이해가 천프로 빠르게 되는 게 급선무
