### ISSUE TITLE
[FEATURE] 닉네임 변경 기능 추가

### ISSUE THREAD

**Issue by SunYerim** [pknu-wap/2023_1_WAT_BeJuRyu#75]
## 📑 작업 사항 
닉네임 변경 기능 추가 및 전역상태관리 설정
서버 연결 준비

## To-do
- [x] 닉네임 변경 기능 추가
- [x] reducer, store 설정
- [x] setupproxy target주소 변경

# #✔️ 기타사항

**Comment by SunYerim** [comment]
일단 서버 api 요청하기 전까지의 작업은 모두 해뒀습니당
혹시 빠진 부분이 있으면 추후 수정
