### ISSUE TITLE
[FEATURE] Review Navigation 설정 및 Ui state 공유 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_1_WAT_BeJuRyu#81]
## 📑 작업 사항 
전반적인 액티비티로 전환을 하니, 하나의 프래그먼트 단위로 전환이 어려워짐. 
activity 걷어내고, app module 단에서 통합적 네비게이션 구현
deep link navigation 구현 

## To-do
- [x] app module 안의 navigation 설정 
- [x] deep link navigation 구현 
- [x] review item ui state 설정을 위한 usecase 구현 

# #✔️ 기타사항
