### ISSUE TITLE
[FEATURE] Analysis 요청 및 조회 api

### ISSUE THREAD

**Issue by onegqueen** [pknu-wap/2023_1_WAT_BeJuRyu#83]
## 📑 작업 사항 
분석된 감정에 대해서 몇가지 기준에 대해 주류를 추천하는 api

## To-do
- [x] 주류추천(분석) 요청 (= 분석 소스 post) api
- [x] 추천받은 주류와 분석된 결과를 조회하는 api
- [x] 이미지 get post 

# #✔️ 기타사항
화이팅
