### ISSUE TITLE
[FEATURE] 전반적인 ui 수정 및 주류 추천결과 코드 수정

### ISSUE THREAD

**Issue by SunYerim** [pknu-wap/2023_1_WAT_BeJuRyu#90]
## 📑 작업 사항 
전반적인 ui 수정 및 주류 추천결과 코드 수정

## To-do
- [x] 전반적인 ui 수정
- [x] 주류 추천결과 코드 -> 이미지, 일기 분리되어 있는 것 통합해서 서버 전송코드까지 구현
- [x] 주류 사전 페이지 (각 주류에 보이는 페이지)

# #✔️ 기타사항
