### ISSUE TITLE
[CHORE] DTO, Model 네이밍 수정 및 필드 추가 및 네이밍 수정

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_1_WAT_BeJuRyu#93]
## 📑 작업 사항 
Dto, Model 네이밍 수정 및 DTO 필드 네이밍 수정
image multipart -> base 64 수정 
이름으로 검색 기능 구현 

## To-do
- [x] Dto, Model 네이밍 수정 및 DTO 필드 네이밍 수정
- [x] base64 전용 binding adapter 구현 
- [x] 주류 이름으로 검색 기능 구현 

# #✔️ 기타사항
