### ISSUE TITLE
[FEATURE] 이용 기록 상세 페이지 구현 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_1_WAT_BeJuRyu#95]
## 📑 작업 사항 
이용 기록 상세 페이지 구현
히스토리 id로 상세 정보 호출 및 응답 처리 
사용자의 입력 정보 + 주류 정보 + 감정 보여주는 ui 구현 및 데이터 매핑 

## To-do
- [ ] 히스토리 검색 기능 구현 
- [ ] 상세 이용기록 ui 구현 
- [ ] 이용기록 리스트 ui 업데이트 

# #✔️ 기타사항
