### ISSUE TITLE
[FEATURE] 이용약관 및 개인정보 사항 추가 

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_1_WAT_BeJuRyu#96]
## 📑 작업 사항 
사용자 입력시 참고할 만한 tip 추가 및 리뷰 작성시 주류 정보 불러오기

## To-do
- [x] 리뷰에 주류 정보 추가하기
- [x] 텍스트 작성 tip 추가
- [x] 이미지 입력 tip 추가

# #✔️ 기타사항
