### ISSUE TITLE
[FEATURE] 사용자 입력 정보 전달 및 주류 추천 페이지 구현

### ISSUE THREAD

**Issue by jeongjaino** [pknu-wap/2023_1_WAT_BeJuRyu#97]
## 📑 작업 사항 
사용자 입력 정보 전달하고 응답 처리 
주류 추천 화면 UI 구현

## To-do
- [x] 입력 정보 모아서 서버로 전달 
- [x] 주류 추천화면 UI 구현 
- [x] 주류 추천 결과 받아와 Ui에 매핑

# #✔️ 기타사항

**Comment by jeongjaino** [comment]
GetAnalysisSentimentDataSourceImpl 궁극의 34자 클래스 네이밍 어떄~
